### ISSUE TITLE
Compatibility with I2C ADC

### ISSUE THREAD

**Issue by clayton-cg** [Spirik/KeyDetector#6]
Hi Spirik, 

Thanks for all of your work on this library. I'm working on setting up a menu with GEM for an ESP32 based controller project. We are using the https://github.com/RobTillaart/ADS1X15 library to read our two analog joysticks with an ADS1115 ADC that communicates with the ESP32 via I2C. The library has a readADC(int channel) function which returns an integer value from 0 to 4096. Is there a way we can set a threshold on this value to read an UP/DOWN/LEFT/RIGHT key press with KeyDetector?

Thanks for your help!
Clayton

**Comment by Spirik** [comment]
Hi Clayton!

KeyDetector only listens to change on pins, so, I am afraid, it won't be able to react to value that is returned from an external function.

At this point it may be easier to write your own implementation of basic KeyDetector functionality, i.e. parse that value you've got from the function and pass it down to GEM (see [Control menu from your sketch](https://github.com/Spirik/GEM/wiki/How-to#control-menu-from-your-sketch) section in GEM wiki). But keep in mind, that given continuous nature of analog signal (even though digitized) it may be tricky to implement discrete button navigation through menu items.
